# $FreeBSD$

PORTNAME=pooler
CATEGORIES=biology
MASTER_SITES=https://ssb22.user.srcf.net/pooler/
DISTNAME=pooler
EXTRACT_SUFX=.tgz
LICENSE=APACHE20
USES=gmake
MAINTAINER=ssb22@cam.ac.uk
COMMENT=PrimerPooler: optimise primer-set combinations

.include <bsd.port.mk>
