# $FreeBSD$

PORTNAME=pooler
DISTVERSION=1.73
CATEGORIES=biology

MAINTAINER=ssb22@cam.ac.uk
COMMENT=PrimerPooler: optimise primer-set combinations

LICENSE=APACHE20

MAKE_FLAGS=-C pooler -f
USES=gmake

USE_GITHUB=yes
GH_ACCOUNT=ssb22
GH_PROJECT=PrimerPooler
GH_TAGNAME=v1.73

PLIST_FILES=bin/pooler man/man1/pooler.1.gz

.include <bsd.port.mk>
