# $FreeBSD$

PORTNAME=pooler
CATEGORIES=biology
USE_GITHUB=yes
GH_ACCOUNT=ssb22
GH_PROJECT=PrimerPooler
DISTVERSION=1.73
GH_TAGNAME=v1.73
MAKE_FLAGS=-C pooler -f
LICENSE=APACHE20
USES=gmake
MAINTAINER=ssb22@cam.ac.uk
COMMENT=PrimerPooler: optimise primer-set combinations

.include <bsd.port.mk>
