name: FreeBSD update
run-name: create diff for updating FreeBSD port
on: [workflow_dispatch]
jobs:
  Create-diff:
    runs-on: ubuntu-latest
    name: create diff
    steps:
    - uses: actions/checkout@v4
    - name: create diff for FreeBSD port update
      uses: cross-platform-actions/action@v0.26.0
      with:
        operating_system: freebsd
        version: '14.3'
        run: |
          pkg install -y git bash
          cd freebsd && bash update.sh
    - name: Upload output
      uses: actions/upload-artifact@v4
      with:
        name: diffs
        path: |
          ${{ github.workspace }}/freebsd/Makefile
          ${{ github.workspace }}/freebsd/pooler.mbox
